schunnallnutt_test_dbt_projects:
  target: dev
  outputs:
    dev:
      account: '_'
      user: '_'
      type: snowflake
      role: TRANSFORMER
      warehouse: TRANSFORMING
      database: SAVANNAH_CA_DEV
      schema: DBT_PROJECTS_DEV
      threads: 8
    prod:
      account: '_'
      user: '_'
      type: snowflake
      role: TRANSFORMER
      warehouse: TRANSFORMING
      database: SAVANNAH_CA_DEV
      schema: DBT_PROJECTS_PROD
      threads: 8
